### ISSUE TITLE
CSS not loading in built/published website.

### ISSUE THREAD

**Issue by MakisH** [DE-RSE/learn-and-teach#17]
Console message:

```
Loading failed for the <script> with source “https://de-rse.org/learn-and-teach/assets/js/main.min.js”.
```

When building in GitHub Actions and downloading the build artifacts, the error is:

```
Loading failed for the <script> with source “file:///learn-and-teach/assets/js/main.min.js”.
```

See also discussion in https://github.com/DE-RSE/survey_rse_training/pull/6#issuecomment-1947184071

**Comment by MakisH** [comment]
@jngrad do you maybe have any ideas on how to solve this? I understand that the issue is how we specify the URLs, but I am not sure what exactly we are doing wrong. I have compared with the chapters website, and I don't see anything related being different.

**Comment by jngrad** [comment]
The RSE chapters page at `https://de-rse.org/chapter/` has links like `<link rel="stylesheet" href="/chapter/assets/css/main.css">` which the server resolves as `https://de-rse.org/learn-and-teach/assets/css/main.css`. The Teach and Learn page at `https://de-rse.org/survey_rse_training/` has links like `<link rel="stylesheet" href="/learn-and-teach/assets/css/main.css">` which the server resolves as `https://de-rse.org/learn-and-teach/assets/css/main.css`.

I suspect the issue originates from the `/survey_rse_training/` name, which doesn't match the `/learn-and-teach/` path (related to #18).

**Comment by MakisH** [comment]
Good point, I did not relate the two issues. Then, fixing #18 would also fix the rendering in the published website.

Any clue if this would also fix the build artifacts? (edit - too fast: of course it will not fix it. Any clue what will?)

**Comment by jngrad** [comment]
Could it be that your locally-generated website is made available on localhost via a PHP server? That would explain why everything works from your side.

To get the built artifacts to work on a local machine, one would need to convert all URLs to be relative to the top-level folder (using `../` recursively), instead of being relative to `/survey_rse_training/`. This task an be automated by e.g. Python's [`os.path.relpath()`](https://docs.python.org/3/library/os.path.html#os.path.relpath), although a similar feature probably exists in Ruby.

Are the built artifacts deployed directly to the website, or do they go through sanitizers first? There are services that automatically sanitize HTML files to elide leading `../` from URLs as a security measure, so as to prevent subpages from accessing private files from parent folders.

**Comment by MakisH** [comment]
> Could it be that your locally-generated website is made available on localhost via a PHP server? That would explain why everything works from your side.

I only use what is already in the repository. Does it work for you if you build locally?

> Are the built artifacts deployed directly to the website, or do they go through sanitizers first? There are services that automatically sanitize HTML files to elide leading `../` from URLs as a security measure, so as to prevent subpages from accessing private files from parent folders.

At the moment, GitHub Pages just takes the state directly from the `main` branch, without any explicit further check from our side. I don't know if GitHub does anything like this automatically.

Let's maybe discuss this in a separate issue.

**Comment by CaptainSifff** [comment]
Not sure, if it's a caching thing, but after the renaming there are still some rendering issues on the location.

**Comment by MakisH** [comment]
I guess we are not serving the additional files, but I can see them in the local preview as I am the same user?

**Comment by jngrad** [comment]
I won't be able to do in-depth troubleshooting, as I'm currently on a duty trip.

**Comment by MakisH** [comment]
It was the URL issue (#18), the repository and the website name were still different: https://de-rse.org/learn-and-teach/
